### ISSUE TITLE
New shapes not accessible

### ISSUE THREAD

**Issue by tnhabib** [structurizr/java-quickstart#4]
I updated my dependencies from:
" compile 'com.structurizr:structurizr-client:1.0.0-RC5" 
to 
" compile 'com.structurizr:structurizr-client:+"'

In attempt to grab the lastest structrizr library to use the following the following shapes that I found in the BigBankPlc sample (https://github.com/structurizr/java/blob/master/structurizr-examples/src/com/structurizr/example/BigBankPlc.java):
Shape.WebBrowser
Shape.MobileDeviceLandscape

Please excuse my ignorance as a new user of structrizr and the gradle build system

**Comment by simonbrowndotje** [comment]
The latest version (with the new shapes) hasn't been released onto Maven Central yet, and I will do this in the next couple of weeks. In the meantime, if you want access to the new shapes, I would recommend building your own version of the client library from the source code. Hope that helps!
