### ISSUE TITLE
Classpath dependency in build.gradle

### ISSUE THREAD

**Issue by NathanDotTo** [structurizr/java-quickstart#7]
Hi,

Here we have 1.15.1:

dependencies {
    compile 'com.structurizr:structurizr-client:1.15.1'
}

Whereas we have 1.14.1 here:

https://github.com/structurizr/java/blob/master/docs/getting-started.md

I know that the code is the truth, so I'll assume that this is correct, and that the getting started needs updating.

Regards

Nathan

**Comment by simonbrowndotje** [comment]
The latest version is now 1.17.0, but I've been meaning to delete this repo anyway, so here goes...
